### ISSUE TITLE
python unmet dependencies at 'git push resin master'

### ISSUE THREAD

**Issue by pcabreracamara** [sitch-io/sensor#93]
Hello,

I'm sorry but I'm new to dockers and I found dependencies problems with python packages when try yo push resin master;

[Build]    The following packages have unmet dependencies:
[Build]     python-dev : Depends: libpython-dev (= 2.7.9-1) but it is not going to be installed
[Build]                  Depends: python2.7-dev (>= 2.7.9-1~) but it is not going to be installed
[Build]    E: Unable to correct problems, you have held broken packages.

I try to modify the 'Dockerfile', adding libpython-dev in the package list, but when I repeat the 'git push resin master' looks like this change is ignored.

How can I solve this issue?

Thank you very much,
Pedro

**Comment by ashmastaflash** [comment]
Hi Pedro,

Thanks for reaching out, I'm researching this right now.

Stand by...

**Comment by ashmastaflash** [comment]
Hey Pedro,

Sorry about that.  I re-pinned libc6 (commit d27c819be54e0c8a47ed1034c39afdf012feed98) and it should work from the master branch now.  Pull fresh from github and push to resin.

Let me know if it gives you any more trouble!

-Ash

**Comment by pcabreracamara** [comment]
Thank you, yes I confirm is solved.
